import test from 'node:test';
import assert from 'node:assert/strict';
import RAPIER from '@dimforge/rapier3d-compat';
import {createVehicle,stepVehicleForces,vehiclePose} from '../src/driving-physics.js';
await RAPIER.init();
function fixture(floor=true){const world=new RAPIER.World({x:0,y:-9.81,z:0});if(floor)world.createCollider(RAPIER.ColliderDesc.cuboid(200,.1,200).setTranslation(0,-.1,0));const car=createVehicle(RAPIER,world,{x:0,z:0},0);world.step();const step=(n,input={})=>{for(let i=0;i<n;i++){stepVehicleForces(car,input,1/60);world.step();}return vehiclePose(car);};return{world,car,step};}
test('a stationary chassis cannot turn in place',()=>{const{world,step}=fixture();const p=step(180,{left:1});assert.ok(Math.abs(p.yaw)<.01);world.free();});
test('acceleration, turning, braking and reverse use tire forces',()=>{const{world,step}=fixture();step(120);const p=step(180,{forward:1});assert.ok(p.speed>12&&p.speed<21);assert.ok(p.position.z<-12);const turn=step(60,{forward:1,right:1});assert.ok(turn.yaw<-.1);const brake=step(180,{brake:true});assert.ok(Math.abs(brake.speed)<.1);const reverse=step(120,{backward:1});assert.ok(reverse.speed<-3);world.free();});
test('an airborne car falls and cannot accelerate or steer itself',()=>{const{world,step}=fixture(false);const p=step(45,{forward:1,right:1});assert.ok(p.position.y<-2);assert.ok(Math.abs(p.position.x)<.001&&Math.abs(p.position.z)<.001);assert.equal(p.grounded,false);world.free();});
test('suspension crosses a street edge without a vertical snap',()=>{const{world,car,step}=fixture();world.createCollider(RAPIER.ColliderDesc.cuboid(8,.06,15).setTranslation(0,.06,-20));world.step();step(120);let last=vehiclePose(car),maxJump=0;for(let i=0;i<240;i++){const p=step(1,{forward:1});maxJump=Math.max(maxJump,Math.abs(p.position.y-last.position.y));last=p;}assert.ok(last.position.z<-20);assert.ok(maxJump<.1);assert.ok(last.rotation.w>.95);world.free();});
test('the sedan can start uphill on a 25-degree street',()=>{const world=new RAPIER.World({x:0,y:-9.81,z:0});const angle=25*Math.PI/180;world.createCollider(RAPIER.ColliderDesc.cuboid(30,.1,60).setRotation({x:Math.sin(angle/2),y:0,z:0,w:Math.cos(angle/2)}).setTranslation(0,-.1,0));const car=createVehicle(RAPIER,world,{x:0,z:0},.5);world.step();for(let i=0;i<360;i++){stepVehicleForces(car,i<120?{brake:true}:{forward:1},1/60);world.step();}const p=vehiclePose(car);assert.ok(p.position.z<-3,`car must climb, z=${p.position.z}`);assert.ok(p.speed>2);world.free();});
